### ISSUE TITLE
'BetterCam' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by jfkexperience** [RootKit-Org/New-World-Fishing-Bot#7]
Followed all the steps in readme and bot seems to run for a split second (switches to NW window and casts) and then stops

**Comment by jfkexperience** [comment]
`540.0 960.0
Traceback (most recent call last):
  File "C:\Users\thien\Downloads\New-World-Fishing-Bot-main\main.py", line 178, in <module>
    main()
  File "C:\Users\thien\Downloads\New-World-Fishing-Bot-main\main.py", line 77, in main
    camera = bettercam.create(region=region, output_color="BGRA", max_buffer_len=512)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\__init__.py", line 115, in create
    return __factory.create(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\__init__.py", line 72, in create
    camera = BetterCam(
             ^^^^^^^^^^
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\bettercam.py", line 34, in __init__
    self._duplicator: Duplicator = Duplicator(
                                   ^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, 'The specified device interface or feature level is not supported on this system.', (None, None, None, 0, None))
Exception ignored in: <function BetterCam.__del__ at 0x000002EFE85CA5C0>
Traceback (most recent call last):
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\bettercam.py", line 248, in __del__
    self.release()
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\bettercam.py", line 243, in release
    self.stop()
  File "C:\Users\thien\AppData\Local\Programs\Python\Python312\Lib\site-packages\bettercam\bettercam.py", line 143, in stop
    if self.is_capturing:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'BetterCam' object has no attribute 'is_capturing'`

**Comment by KrushiBezawada** [comment]
I'm having the same error. Couldn't find a fix

**Comment by Qfc9** [comment]
Look here or ask Wonder in the discord
https://github.com/RootKit-Org/AI-Aimbot/issues/133
